{"timestamp":"2025-05-31T15:13:08.926406","level":"info","event":"DAG bundles loaded: dags-folder","logger":"airflow.dag_processing.bundles.manager.DagBundlesManager"}
{"timestamp":"2025-05-31T15:13:08.926976","level":"info","event":"Filling up the DagBag from /opt/airflow/dags/dag_with_minio_s3.py","logger":"airflow.models.dagbag.DagBag"}
{"timestamp":"2025-05-31T15:13:09.078489","level":"info","event":"Poking for key : s3://airflow/data.csv","logger":"airflow.task.operators.airflow.providers.amazon.aws.sensors.s3.S3KeySensor"}
{"timestamp":"2025-05-31T15:13:09.079644","level":"info","event":"Secrets backends loaded for worker","count":1,"backend_classes":["EnvironmentVariablesBackend"],"logger":"supervisor"}
{"timestamp":"2025-05-31T15:13:09.458287","level":"info","event":"Connection Retrieved 'minioS3'","logger":"airflow.hooks.base"}
{"timestamp":"2025-05-31T15:13:09.458472","level":"info","event":"AWS Connection (conn_id='minioS3', conn_type='aws') credentials retrieved from login and password.","logger":"airflow.providers.amazon.aws.utils.connection_wrapper.AwsConnectionWrapper"}
{"timestamp":"2025-05-31T15:14:02.484248","level":"error","event":"Task failed with exception","logger":"task","error_detail":[{"exc_type":"EndpointConnectionError","exc_value":"Could not connect to the endpoint URL: \"http://minio1:9000/airflow/data.csv\"","exc_notes":[],"syntax_error":null,"is_cause":false,"frames":[{"filename":"/home/airflow/.local/lib/python3.12/site-packages/airflow/sdk/execution_time/task_runner.py","lineno":838,"name":"run"},{"filename":"/home/airflow/.local/lib/python3.12/site-packages/airflow/sdk/execution_time/task_runner.py","lineno":1130,"name":"_execute_task"},{"filename":"/home/airflow/.local/lib/python3.12/site-packages/airflow/sdk/bases/operator.py","lineno":408,"name":"wrapper"},{"filename":"/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/amazon/aws/sensors/s3.py","lineno":184,"name":"execute"},{"filename":"/home/airflow/.local/lib/python3.12/site-packages/airflow/sdk/bases/operator.py","lineno":408,"name":"wrapper"},{"filename":"/home/airflow/.local/lib/python3.12/site-packages/airflow/sdk/bases/sensor.py","lineno":227,"name":"execute"},{"filename":"/home/airflow/.local/lib/python3.12/site-packages/airflow/sdk/bases/sensor.py","lineno":207,"name":"execute"},{"filename":"/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/amazon/aws/sensors/s3.py","lineno":178,"name":"poke"},{"filename":"/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/amazon/aws/sensors/s3.py","lineno":150,"name":"_check_key"},{"filename":"/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/amazon/aws/hooks/s3.py","lineno":153,"name":"wrapper"},{"filename":"/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/amazon/aws/hooks/s3.py","lineno":126,"name":"wrapper"},{"filename":"/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/amazon/aws/hooks/s3.py","lineno":934,"name":"head_object"},{"filename":"/home/airflow/.local/lib/python3.12/site-packages/botocore/client.py","lineno":569,"name":"_api_call"},{"filename":"/home/airflow/.local/lib/python3.12/site-packages/botocore/client.py","lineno":1005,"name":"_make_api_call"},{"filename":"/home/airflow/.local/lib/python3.12/site-packages/botocore/client.py","lineno":1029,"name":"_make_request"},{"filename":"/home/airflow/.local/lib/python3.12/site-packages/botocore/endpoint.py","lineno":119,"name":"make_request"},{"filename":"/home/airflow/.local/lib/python3.12/site-packages/botocore/endpoint.py","lineno":200,"name":"_send_request"},{"filename":"/home/airflow/.local/lib/python3.12/site-packages/botocore/endpoint.py","lineno":360,"name":"_needs_retry"},{"filename":"/home/airflow/.local/lib/python3.12/site-packages/botocore/hooks.py","lineno":412,"name":"emit"},{"filename":"/home/airflow/.local/lib/python3.12/site-packages/botocore/hooks.py","lineno":256,"name":"emit"},{"filename":"/home/airflow/.local/lib/python3.12/site-packages/botocore/hooks.py","lineno":239,"name":"_emit"},{"filename":"/home/airflow/.local/lib/python3.12/site-packages/botocore/retryhandler.py","lineno":207,"name":"__call__"},{"filename":"/home/airflow/.local/lib/python3.12/site-packages/botocore/retryhandler.py","lineno":284,"name":"__call__"},{"filename":"/home/airflow/.local/lib/python3.12/site-packages/botocore/retryhandler.py","lineno":320,"name":"_should_retry"},{"filename":"/home/airflow/.local/lib/python3.12/site-packages/botocore/retryhandler.py","lineno":363,"name":"__call__"},{"filename":"/home/airflow/.local/lib/python3.12/site-packages/botocore/retryhandler.py","lineno":247,"name":"__call__"},{"filename":"/home/airflow/.local/lib/python3.12/site-packages/botocore/retryhandler.py","lineno":416,"name":"_check_caught_exception"},{"filename":"/home/airflow/.local/lib/python3.12/site-packages/botocore/endpoint.py","lineno":279,"name":"_do_get_response"},{"filename":"/home/airflow/.local/lib/python3.12/site-packages/botocore/endpoint.py","lineno":383,"name":"_send"},{"filename":"/home/airflow/.local/lib/python3.12/site-packages/botocore/httpsession.py","lineno":493,"name":"send"}]},{"exc_type":"NameResolutionError","exc_value":"<botocore.awsrequest.AWSHTTPConnection object at 0x7ee1c8431e50>: Failed to resolve 'minio1' ([Errno -3] Temporary failure in name resolution)","exc_notes":[],"syntax_error":null,"is_cause":false,"frames":[{"filename":"/home/airflow/.local/lib/python3.12/site-packages/botocore/httpsession.py","lineno":464,"name":"send"},{"filename":"/home/airflow/.local/lib/python3.12/site-packages/urllib3/connectionpool.py","lineno":841,"name":"urlopen"},{"filename":"/home/airflow/.local/lib/python3.12/site-packages/urllib3/util/retry.py","lineno":449,"name":"increment"},{"filename":"/home/airflow/.local/lib/python3.12/site-packages/urllib3/util/util.py","lineno":39,"name":"reraise"},{"filename":"/home/airflow/.local/lib/python3.12/site-packages/urllib3/connectionpool.py","lineno":787,"name":"urlopen"},{"filename":"/home/airflow/.local/lib/python3.12/site-packages/urllib3/connectionpool.py","lineno":493,"name":"_make_request"},{"filename":"/home/airflow/.local/lib/python3.12/site-packages/botocore/awsrequest.py","lineno":96,"name":"request"},{"filename":"/home/airflow/.local/lib/python3.12/site-packages/urllib3/connection.py","lineno":445,"name":"request"},{"filename":"/usr/local/lib/python3.12/http/client.py","lineno":1333,"name":"endheaders"},{"filename":"/home/airflow/.local/lib/python3.12/site-packages/botocore/awsrequest.py","lineno":123,"name":"_send_output"},{"filename":"/home/airflow/.local/lib/python3.12/site-packages/botocore/awsrequest.py","lineno":223,"name":"send"},{"filename":"/usr/local/lib/python3.12/http/client.py","lineno":1037,"name":"send"},{"filename":"/home/airflow/.local/lib/python3.12/site-packages/urllib3/connection.py","lineno":276,"name":"connect"},{"filename":"/home/airflow/.local/lib/python3.12/site-packages/urllib3/connection.py","lineno":205,"name":"_new_conn"}]},{"exc_type":"gaierror","exc_value":"[Errno -3] Temporary failure in name resolution","exc_notes":[],"syntax_error":null,"is_cause":true,"frames":[{"filename":"/home/airflow/.local/lib/python3.12/site-packages/urllib3/connection.py","lineno":198,"name":"_new_conn"},{"filename":"/home/airflow/.local/lib/python3.12/site-packages/urllib3/util/connection.py","lineno":60,"name":"create_connection"},{"filename":"/usr/local/lib/python3.12/socket.py","lineno":978,"name":"getaddrinfo"}]}]}
